### ISSUE TITLE
create spreadsheets webpage

### ISSUE THREAD

**Issue by QueMona98** [hack4impact-calpoly/one-cool-earth#40]
I don't have much documentation for this other than to use the following link containing Sarah's draft for the website design as a guide for creating this component:

https://www.figma.com/file/nZVcNd2NGOmjHQQGtiRtsj/OCE-Wireframing?node-id=0%3A1

The main part of this issue is to create different sections on the web page as seen in the design (header, section for the button in the header, the body which will include the spreadsheet). Don't worry TOO much about how you chose to implement this--the purpose of this issue is to just get the skeleton on the web page. We have buttons and card components being made that will be placed onto this "skeleton" later.

For background about what this page is supposed to do/will look like, this is just a way for the administrator to view all of the volunteers in the system. So when coding the webpage, think of an excel spreadsheet. Each column corresponds to a field of the user, and each row corresponds to a User.

If you are up for the task, you can try implementing it with this package:
https://www.npmjs.com/package/react-spreadsheet

If not, just display data is a spreadsheet like fashion in plain old html and we (you, me or someone else) can come back to fine-tune this web page later. 

I am giving you this option because we just need to get the basics/skeleton of the webpages and we can come back and build on top of it later.

Don't hesitate to reach out to me if you are unsure about how to start, but I ask that you run your finished product by Sarah and I before you make a pull request!

**Comment by jlrJames** [comment]
Spreadsheet james pull request finishes this issue. (Forgot to close the issue, until now)
Switched to a different spreadsheet package and the spreadsheet is cenetered on the webpage as seen in the figma.
