### ISSUE TITLE
write endpoint for getting user volunteer dates

### ISSUE THREAD

**Issue by QueMona98** [hack4impact-calpoly/one-cool-earth#63]
Because this functionality is going to be reused throughout the app, let's just write a function that can be called anytime we want to get a user's volunteer dates. Of course, this is assuming that the user has already signed in/been authenticated.

Moreover, create a directory in "src" titled "actions" That way we have a clearly defined directory to store reusable actions/logic. Title the file "retrieveUserEvents.js"

**Comment by rohit267** [comment]
let me try

**Comment by rohit267** [comment]
requesting CLIENT_ID and CLIENT_SECRET for configs.

**Comment by rohit267** [comment]
there are already pending issues, without fixing those how can we implement google login as there is no button

**Comment by QueMona98** [comment]
Hello Rohit! I understand that this is a public repo, but are you apart of Hack4Impact? Unfortunately, the issues and repo are not open to be worked on by anyone that isn't apart of Hack4Impact.

**Comment by rohit267** [comment]
ok thanks for confirmation, you should add custom label of Hack4Impact or provide some information on Readme.

**Comment by QueMona98** [comment]
Will do! Thank you for the feedback and I appreciate your inclination to help contribute.
